### ISSUE TITLE
Would like a stdin switch option

### ISSUE THREAD

**Issue by svanellewee** [svanellewee/SchemerFuzzer#2]
The tool usually gets used like this:

    #! schmrfzzr --input examples/test-regex.json --output bla.json

But what would be nice is if we can provide input from stdin using other commandline tools, for example (Note the dash at the end to denote stdin):

    #!  echo '{"type": "string"}' | schmrfzzr --output bla.json  --input -

**Comment by artslob** [comment]
I will try this one

**Comment by svanellewee** [comment]
Cool! Go for it let me know if anything's vague.

**Comment by artslob** [comment]
@svanellewee Actually I already implemented it, check it #3
